export enum MovementType {
  ENTRADA = 'ENTRADA',
  VENTA = 'VENTA',
  DAÑO = 'DAÑO',
  VENCIMIENTO = 'VENCIMIENTO',
  DEVOLUCION = 'DEVOLUCION',
  AJUSTE_INGRESO = 'AJUSTE_INGRESO',
  AJUSTE_SALIDA = 'AJUSTE_SALIDA',
  TRASLADO = 'TRASLADO',
}
